openapi: 3.0.0
info:
  description: IOBuilders-Bank
  version: "1.0.0"
  title: This is a Rest API for ioBuilders-bank
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: /v1
tags:
  - name: Users
    description: Operations about users
  - name: Accounts
    description: Operations about accounts
  - name: Transactions
    description: Operations about transactions
paths:
  /users:
    post:
      tags:
      - Users
      summary: Register a new user
      description: Register a user in the system
      operationId: register_user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserRequest'
        required: true
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'

  /accounts:
    post:
      tags:
        - Accounts
      summary: New Account
      description: Create a new account
      operationId: create_account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequest'
        required: true
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'

  /accounts/{accountId}:
    patch:
      tags:
      - Accounts
      summary: Account deposit
      description: Update account Balance
      operationId: update_account_balance
      parameters:
      - name: accountId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          maxLength: 36
          pattern: \b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountDepositRequest'
        required: true
      responses:
        200:
          description: UPDATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'

  /accounts/{accountId}/balances:
    get:
      tags:
        - Accounts
      summary: Accounts
      description: Retrieve account balance
      operationId: get_account_balance
      parameters:
        - name: accountId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            maxLength: 36
            pattern: \b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountBalanceResponse'

  /accounts/{accountId}/transactions:
    get:
      tags:
        - Accounts
      summary: Accounts
      description: Retrieve all transactions for an account
      operationId: get_account_transactions
      parameters:
        - name: accountId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            maxLength: 36
            pattern: \b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountTransactionsResponse'

  /transactions:
    post:
      tags:
      - Transactions
      summary: New Transaction
      description: Create a new Transaction
      operationId: create_transaction
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRequest'
        required: true
      responses:
        201:
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'

components:
  schemas:
    RegisterUserRequest:
      type: object
      required:
        - username
      properties:
        username:
          maxLength: 50
          pattern: /^[a-z ,.'-]+$/i
          type: string
          example: johndoe
        firstName:
          maxLength: 50
          pattern: /^[a-z ,.'-]+$/i
          type: string
          example: John
        lastName:
          maxLength: 50
          pattern: /^[a-z ,.'-]+$/i
          type: string
          example: Doe
        email:
          maxLength: 50
          pattern: (?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])
          type: string
          example: jdoe@iobuilders.com
    UserResponse:
      type: object
      properties:
        userId:
          maxLength: 36
          pattern: \b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b
          type: string
          format: uuid
          example: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        username:
          maxLength: 50
          pattern: /^[a-z ,.'-]+$/i
          type: string
          example: johndoe
        firstName:
          maxLength: 50
          pattern: /^[a-z ,.'-]+$/i
          type: string
          example: John
        lastName:
          maxLength: 50
          pattern: /^[a-z ,.'-]+$/i
          type: string
          example: Doe
        email:
          pattern: (?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])
          type: string
          example: jdoe@iobuilders.com

    CreateAccountRequest:
      type: object
      required:
        - userId
      properties:
        userId:
          maxLength: 36
          pattern: \b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b
          type: string
          format: uuid
    AccountDepositRequest:
      type: object
      required:
        - amount
      properties:
        amount:
          type: number
          example: 00.00
    AccountBalanceResponse:
      type: object
      properties:
        accountId:
          maxLength: 36
          pattern: \b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b
          type: string
          format: uuid
          example: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        iban:
          maxLength: 24
          pattern: ([a-zA-Z]{2})\s*\t*(\d{2})\s*\t*(\d{4})\s*\t*(\d{4})\s*\t*(\d{2})\s*\t*(\d{10})
          type: string
          example: ES0000000000000000000000
        balance:
          maximum: 90000000000000
          minimum: 0
          type: number
          example: 00.00
    AccountTransactionsResponse:
      type: object
      properties:
        accountId:
          maxLength: 36
          pattern: \b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b
          type: string
          format: uuid
          example: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        transactions:
          $ref: '#/components/schemas/TransactionsResponse'
    AccountResponse:
      type: object
      properties:
        accountId:
          maxLength: 36
          pattern: \b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b
          type: string
          format: uuid
          example: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        iban:
          maxLength: 24
          pattern: ([a-zA-Z]{2})\s*\t*(\d{2})\s*\t*(\d{4})\s*\t*(\d{4})\s*\t*(\d{2})\s*\t*(\d{10})
          type: string
          example: ES0000000000000000000000
        owner:
          type: string
          example: /users/ca53bbc5-c35c-4b5c-8095-0d154ab8d6c7
        amount:
          maximum: 90000000000000
          minimum: 0
          type: number
          example: 00.00

    TransactionRequest:
      type: object
      required:
        - amount
        - destinationAccountId
        - originAccountId
      properties:
        amount:
          maximum: 90000000000000
          minimum: 0
          type: number
          example: 00.00
        destinationAccountId:
          maxLength: 36
          pattern: \b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b
          type: string
          format: uuid
          example: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        originAccountId:
          maxLength: 36
          pattern: \b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b
          type: string
          format: uuid
          example: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    TransactionResponse:
      type: object
      properties:
        transactionId:
          type: string
          format: uuid
          example: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        amount:
          type: number
          example: 00.00
        destinationAccountIban:
          maxLength: 24
          pattern: ([a-zA-Z]{2})\s*\t*(\d{2})\s*\t*(\d{4})\s*\t*(\d{4})\s*\t*(\d{2})\s*\t*(\d{10})
          type: string
          example: ES0000000000000000000000
        originAccountIban:
          maxLength: 24
          pattern: ([a-zA-Z]{2})\s*\t*(\d{2})\s*\t*(\d{4})\s*\t*(\d{4})\s*\t*(\d{2})\s*\t*(\d{10})
          type: string
          example: ES0000000000000000000000
        transactionDate:
          type: string
          format: date-time
    TransactionsResponse:
      type: object
      properties:
        results:
          maximum: 900
          minimum: 0
          type: number
          example: 1
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/TransactionResponse'

