openapi: 3.0.0
info:
  description: IOBuilders-Bank
  version: "1.0.0"
  title: This is a Rest API for ioBuilders-bank
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: /v1
tags:
  - name: Users
    description: Operations about users
  - name: Accounts
    description: Operations about accounts
  - name: Transactions
    description: Operations about transactions
paths:
  /users:
    post:
      tags:
      - Users
      summary: Create new user
      description: Register a user in the system
      operationId: create_user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
        required: true
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
  /users/{userId}:
    get:
      tags:
      - Users
      summary: Get user info
      description: Retrieve user information
      operationId: get_user_by_id
      parameters:
      - name: userId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          maxLength: 36
          pattern: \b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b
          type: string
          format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
    delete:
      tags:
        - Users
      summary: Delete user
      description: Delete user information
      operationId: delete_user
      parameters:
        - name: userId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            maxLength: 36
            pattern: \b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b
            type: string
            format: uuid
      responses:
        204:
          description: No content

  /accounts:
    post:
      tags:
        - Accounts
      summary: New Account
      description: Create a new account
      operationId: create_account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequest'
        required: true
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
    get:
      tags:
      - Accounts
      summary: Accounts
      description: Retrieve a list of accounts
      operationId: get_accounts
      parameters:
      - name: userId
        in: query
        required: false
        style: form
        explode: true
        schema:
          maxLength: 36
          pattern: \b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b
          type: string
          format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountsResponse'
  /accounts/{accountId}:
    get:
      tags:
      - Accounts
      summary: Account info
      description: Retrieve account information
      operationId: get_account_by_id
      parameters:
      - name: accountId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          maxLength: 36
          pattern: \b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b
          type: string
          format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
    patch:
      tags:
      - Accounts
      summary: Update account Amount
      description: Update account Balance
      operationId: update_account
      parameters:
      - name: accountId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          maxLength: 36
          pattern: \b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAccountRequest'
        required: true
      responses:
        200:
          description: UPDATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
  /transactions:
    get:
      tags:
      - Transactions
      summary: Account Transactions
      description: Get Transactions by account
      operationId: get_transactions
      parameters:
      - name: originAccountIban
        in: query
        required: false
        style: form
        explode: true
        schema:
          maxLength: 24
          pattern: ([a-zA-Z]{2})\s*\t*(\d{2})\s*\t*(\d{4})\s*\t*(\d{4})\s*\t*(\d{2})\s*\t*(\d{10})
          type: string
      - name: destinationAccountIban
        in: query
        required: false
        style: form
        explode: true
        schema:
          maxLength: 24
          pattern: ([a-zA-Z]{2})\s*\t*(\d{2})\s*\t*(\d{4})\s*\t*(\d{4})\s*\t*(\d{2})\s*\t*(\d{10})
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionsResponse'
    post:
      tags:
      - Transactions
      summary: New Transaction
      description: Create new Transaction
      operationId: create_transaction
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRequest'
        required: true
      responses:
        201:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
  /transactions/{transactionId}:
    get:
      tags:
      - Transactions
      summary: Transaction info
      description: Get Transaction info by transactionId
      operationId: get_transaction_by_id
      parameters:
      - name: transactionId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          maxLength: 36
          pattern: \b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b
          type: string
          format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
components:
  schemas:
    UserRequest:
      type: object
      required:
        - username
      properties:
        username:
          maxLength: 50
          pattern: /^[a-z ,.'-]+$/i
          type: string
          example: johndoe
        firstName:
          maxLength: 50
          pattern: /^[a-z ,.'-]+$/i
          type: string
          example: John
        lastName:
          maxLength: 50
          pattern: /^[a-z ,.'-]+$/i
          type: string
          example: Doe
        email:
          maxLength: 50
          pattern: (?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])
          type: string
          example: jdoe@iobuilders.com
    UserResponse:
      type: object
      properties:
        userId:
          maxLength: 36
          pattern: \b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b
          type: string
          format: uuid
          example: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        username:
          maxLength: 50
          pattern: /^[a-z ,.'-]+$/i
          type: string
          example: johndoe
        firstName:
          maxLength: 50
          pattern: /^[a-z ,.'-]+$/i
          type: string
          example: John
        lastName:
          maxLength: 50
          pattern: /^[a-z ,.'-]+$/i
          type: string
          example: Doe
        email:
          pattern: (?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])
          type: string
          example: jdoe@iobuilders.com
    TransactionsResponse:
      type: object
      properties:
        results:
          maximum: 900
          minimum: 0
          type: number
          example: 1
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/TransactionResponse'
    TransactionRequest:
      type: object
      required:
        - amount
        - destinationAccountIban
        - originAccountIban
      properties:
        amount:
          maximum: 90000000000000
          minimum: 0
          type: number
          example: 00.00
        destinationAccountIban:
          maxLength: 24
          pattern: ([a-zA-Z]{2})\s*\t*(\d{2})\s*\t*(\d{4})\s*\t*(\d{4})\s*\t*(\d{2})\s*\t*(\d{10})
          type: string
          example: ES0000000000000000000000
        originAccountIban:
          maxLength: 24
          pattern: ([a-zA-Z]{2})\s*\t*(\d{2})\s*\t*(\d{4})\s*\t*(\d{4})\s*\t*(\d{2})\s*\t*(\d{10})
          type: string
          example: ES0000000000000000000000
    TransactionResponse:
      type: object
      properties:
        transactionId:
          type: string
          format: uuid
          example: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        amount:
          type: number
          example: 00.00
        destinationAccountIban:
          maxLength: 24
          pattern: ([a-zA-Z]{2})\s*\t*(\d{2})\s*\t*(\d{4})\s*\t*(\d{4})\s*\t*(\d{2})\s*\t*(\d{10})
          type: string
          example: ES0000000000000000000000
        originAccountIban:
          maxLength: 24
          pattern: ([a-zA-Z]{2})\s*\t*(\d{2})\s*\t*(\d{4})\s*\t*(\d{4})\s*\t*(\d{2})\s*\t*(\d{10})
          type: string
          example: ES0000000000000000000000
        transactionDate:
          type: string
          format: date-time
    CreateAccountRequest:
      type: object
      required:
        - userId
      properties:
        userId:
          maxLength: 36
          pattern: \b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b
          type: string
          format: uuid
    UpdateAccountRequest:
      type: object
      required:
        - amount
        - operation
      properties:
        amount:
          type: number
          example: 00.00
        operation:
          type: string
          nullable: false
          enum:
            - add
            - substract
    AccountResponse:
      type: object
      properties:
        accountId:
          maxLength: 36
          pattern: \b[0-9a-f]{8}\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}\b
          type: string
          format: uuid
          example: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        iban:
          maxLength: 24
          pattern: ([a-zA-Z]{2})\s*\t*(\d{2})\s*\t*(\d{4})\s*\t*(\d{4})\s*\t*(\d{2})\s*\t*(\d{10})
          type: string
          example: ES0000000000000000000000
        owner:
          type: string
          example: /users/ca53bbc5-c35c-4b5c-8095-0d154ab8d6c7
        amount:
          maximum: 90000000000000
          minimum: 0
          type: number
          example: 00.00
    AccountsResponse:
      type: object
      properties:
        results:
          maximum: 900
          minimum: 0
          type: number
          example: 1
        accounts:
          type: array
          items:
            $ref: '#/components/schemas/AccountResponse'
